### ISSUE TITLE
Source doesn't get marked as hidden when finished

### ISSUE THREAD

**Issue by codemann8** [cg2121/obs-visibility-timer#1]
I think this might be an underlying problem with the API, but I thought I'd bring it up, because it causes problems in trying to have this script activate multiple times in a row, which requires the user to manually "hide" the source again before showing it again.

Another issue, I have a browser source showing a YouTube video, and when the script "hides" the video, the video does go away but the audio continues to play until I manually hide the source.

**Comment by cg2121** [comment]
Fixed with https://github.com/cg2121/obs-visibility-timer/commit/924c92b133d1b7422b75c8e4aa14a67dad54500a
