### ISSUE TITLE
Timer does not work in Studio Mode

### ISSUE THREAD

**Issue by fringer-v** [cg2121/obs-visibility-timer#4]
Your change from using the "source_activate" to "source_show" signal has caused a regression when Studio Mode. In this case, the timer is not started when cutting to the scene with the timer.

The problem is that "source_show" signal is triggered when you select the scene with the timer in the preview. Then when you cut to this scene, the "source_show" signal is **not triggered** again because the element is already visible. As a result the timer is not started.

**Comment by cg2121** [comment]
Should be fixed with https://github.com/cg2121/obs-visibility-timer/commit/924c92b133d1b7422b75c8e4aa14a67dad54500a
